Repository BoraxTheClean/adaptable-antelopes, pull requests merged in 2021-07, with the labels that each got.

#8 Add pytest back to dev-requirements.txt
  dev-requirements.txt
Labels: needs-review

#5 Add black step to pre-commit
  .pre-commit-config.yaml
Labels: enhancement, needs-review

#15 Make main green
  .pre-commit-config.yaml
  scroll_menu.py
  text_editor.py
  tox.ini
Labels: needs-review

#18 Change menu keybind
  text_editor.py
Labels: needs-review

#23 Directory refactor
  scroll_menu.py
  src/application_entry.py
  src/custom_types/ui_types.py
  src/scroll/scroll_menu.py
  src/text/text_editor.py
Labels: needs-review

#26 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
  src/scroll/scroll_menu.py
Labels: needs-review

#46 Append NOTES_DIR/ to newly saved files
  src/text/text_editor.py
Labels: needs-review

#49 menu bar: text to emoji change
  README.md
  dev-requirements.txt
  src/navigation/menu_bar.py
Labels: needs-review

#60 Add run script decouple dependencies
  README.md
  dev-requirements.txt
  requirements.txt
  run.sh
Labels: needs-review

#58 Add welcome page
  src/application/editor.py
  src/application/state.py
  src/assets/welcome.md
  src/constants.py
Labels: needs-review

#59 Hide hidden files
  src/custom_types/scroll_menu.py
  src/navigation/menu_bar.py
Labels: needs-review

#72 Comments and Random NitPicks
  src/application/editor.py
  src/custom_types/scroll_menu.py
  src/custom_types/text_input.py
  src/navigation/menu_bar.py
Labels: needs-review

#73 Document Hotkeys
  README.md
Labels: needs-review

#83 Color picker
  README.md
  src/application/editor.py
  src/application/state.py
  src/constants.py
  src/custom_types/__init__.py
  src/custom_types/color_picker.py
  src/custom_types/text_input.py
  src/navigation/menu_bar.py
Labels: enhancement
